### ISSUE TITLE
Feature request: allow for callback for additional handling when error

### ISSUE THREAD

**Issue by duydnguyen07** [daiscog/ngx-http-request-state#5]
Currently, we cannot use your library and do additional error handling task.

What if there is a way to pass in a callback function into the **httpRequestStates()** for example. 

```
pipe(
  httpRequestStates({
     errorCallBack: () => { my error handling logic }
  })
)
```

**Comment by daiscog** [comment]
Hi - thanks for the suggestion.

However, the current behaviour is deliberate, and by design.  The intention is the operator converts an input observable based on an HTTP request to a stream of _events_ surrounding that request.  If the request errors, the operator emits an ErrorState event.

There are lots of options available for error handling, using existing RxJs techniques.  For example, as mentioned by @thor84no above, you could add another operator that handles ErrorState _after_ the `httpRequestStates` operator, or you could insert a `catchError` in your pipe _before_ the `httpRequestStates` operator.
