### ISSUE TITLE
The library is really nice but does it really need angular as a dependency?

### ISSUE THREAD

**Issue by duydnguyen07** [daiscog/ngx-http-request-state#6]
We would like to use this library in our project but the strict tie to angular is making it less attractive. Can we just lower the version of angular to minimum of version 8 or something?

**Comment by daiscog** [comment]
Hi @duydnguyen07 

Thank you for your interest.

> does it really need angular as a dependency?

Angular is a _peer_ dependency, and needs to be so because this library imports from Angular.

> Can we just lower the version of angular to minimum of version 8 or something?

Version 1.2.0 of this library supports Angular 8 to 13.  Use this version for Angular 8 apps.

Version 2.0.0 raised the minimum version of Angular to 14. 

![Screenshot 2022-08-09 at 16 41 00](https://user-images.githubusercontent.com/5968668/183698964-3ab9c7ce-8cdf-4c24-8d2f-2de03e14a9f9.png)
